### ISSUE TITLE
Plan for serde_dynamo 4

### ISSUE THREAD

**Issue by bryanburgers** [zenlist/serde_dynamo#23]
The plan for `serde_dynamo` version 4 will be:

* Support aws-sdk version 1.0
* Drop support for rusoto

`serde_dynamo` version 3 (published today) effectively supports both aws-sdk and rusoto based on feature flags. It does this because neither of those libraries has reached 1.0; without feature-flag support, any minor version bump to those libraries would require a major version bump to `serde_dynamo`.

In version 4, we plan to drop support for rusoto. Rusoto is currently in ["maintenance mode"](https://github.com/rusoto/rusoto/tree/e9d921492ffb020d0d80aaf5438f3eb865941ee4#maintenance-status), so version 3 will continue to support it and there is no reason to continue to support it into version 4 and beyond.

When aws-sdk reaches version 1.0, we can drop the feature flags and just support version 1.0 because at that point, minor bumps to aws-sdk version 1.0 will not require a re-release of `serde_dynamo`.

**Comment by bryanburgers** [comment]
Change of plans.

* I don't think the community will coalesce around one single definition of `AttributeValue`. I was hoping that `aws_sdk_dynamodb::model::AttributeValue` would be _the_ `AttributeValue`, but even `aws_sdk_dynamodbstreams` won't adopt it as the de-facto definition.
* The [AttributeValue trait definition in v3][AttributeValue trait], as defined, does not work [aws_lambda_event's AttributeValue][AttributeValue aws_lambda_events]. That makes it hard to complete #24 and #35.
* The [AttributeValue trait definition in v3][AttributeValue trait] also caused the compile time of one of Zenlist's key projects to balloon from 20 minutes to 40 minutes, so we never upgraded from v2 to v3.

Given all of that, I looked into a new way to approach this library, and settled on the following.

* `serde_dynamo` v4 will define it's own `AttributeValue` enum.
* `serde_dynamo` v4 will implement `From<external_crate::AttributeValue> for AttributeValue` and `From<AttributeValue> for external_crate::AttributeValue` based on features, to make it easy to convert between e.g. `aws_sdk_dynamodb::model::AttributeValue` and `serde_dynamo::AttributeValue`.
* Functions like `from_attribute_value`/`to_attribute_value` will deal with anything that is `From<AttributeValue>`/`Into<AttributeValue>` to provide an API that is almost exactly like the v3 API.

[AttributeValue trait]: https://docs.rs/serde_dynamo/3/serde_dynamo/trait.AttributeValue.html
[AttributeValue aws_lambda_events]: https://docs.rs/aws_lambda_events/0.6.2/aws_lambda_events/dynamodb/attributes/enum.AttributeValue.html

**Comment by mbergkvist** [comment]
This "new type" approach is similar approach I took in my project to convert from  the aws_lambda_event AttributeValue to aws_sdk AttributeValue, which I could then use with serde_dynamo 3.
