### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by lcmgh** [zenlist/serde_dynamo#33]
First of all thanks for that really useful trait. I just could not get it working with latest aws sdk dynamodb version 0.10.1.

Error:
```
the trait bound `aws_sdk_dynamodb::model::AttributeValue: serde_dynamo::AttributeValue` is not satisfied
the trait `serde_dynamo::AttributeValue` is not implemented for `aws_sdk_dynamodb::model::AttributeValue`
```

when calling
```rust
let rows: Vec<LeaseTableRow> = from_items(items)?;
```

while `items` is of type `items: Vec<HashMap<String, AttributeValue>>`

Edit: Downgrading to 0.10.0 gives me the same error.
Edit 2: Changing my dependency to `serde_dynamo = { version = "3.0.3", features = ["full"] }` fixed the issue. Wasn't aware of that as there was no hint in the README.

**Comment by bryanburgers** [comment]
This is documented at https://docs.rs/serde_dynamo/latest/serde_dynamo/#features and at https://docs.rs/serde_dynamo/latest/serde_dynamo/#aws-sdk-support.

You mention it’s not on the README. You were looking at the GitHub page on the readme for this information, and not on docs.rs? If there was a link from the README to the features section on docs.rs, would that have helped?

**Comment by lcmgh** [comment]
>> If there was a link from the README to the features section on docs.rs, would that have helped?

Yes.

It would also have helped to enrich the example with a hint to the necessary feature. I assumed I don't need anything else beside the base dependency.

**Comment by bryanburgers** [comment]
OK. Would you be willing to submit a PR with what you think would have helped you get up to speed faster?

Yeah, I’d love for `serde_dynamo` to *just work* without any features required, but unfortunately that’s not feasible at this point.

**Comment by bryanburgers** [comment]
A [features section](https://github.com/zenlist/serde_dynamo#features) has been added to the README.
