### ISSUE TITLE
Don't serialize Option None

### ISSUE THREAD

**Issue by nuvacore** [zenlist/serde_dynamo#43]
Is it possible to not serialize and Option if it's value is None? And not error out but interpret a missing Option field as None when deserializing?

The reason I would like this behavior is that it would save a lot of space in DynamoDb with lots of optional fields.

If this is not supported today, what would be needed to support it?

**Comment by bryanburgers** [comment]
I definitely understand the request. There are times I have wished serde made this easier.

At the same time, serde_dynamo aims to be as consistent as possible with the rest of the serde ecosystem, and especially consistent with serde_json.

To be consistent, serde_dynamo serializes Nones as DynamoDb nulls. To change this behavior, use the attribute `#[serde(skip_serializing_if = "Option::is_none")]`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c2cd213070647cfe92d8c4dd2312fa59
