### ISSUE TITLE
I wish there were a `from_items` function

### ISSUE THREAD

**Issue by dcormier** [zenlist/serde_dynamo#5]
I wish there were a `from_items` function for deserializing `Vec<HashMap<String, AttributeValue>>` en masse. For deserilizing [`QueryOutput.items`](https://rusoto.github.io/rusoto/rusoto_dynamodb/struct.QueryOutput.html#structfield.items), for example.

**Comment by bryanburgers** [comment]
Yeah, that totally makes sense! If you create a pull request for it with some good tests, that's something that could definitely be merged.

Are you thinking something like this?

```rust
pub fn from_items<'a, T>(items: Vec<Item>) -> Result<Vec<T>>
where
    T: Deserialize<'a>
{
    todo!()
}
```

**Comment by dcormier** [comment]
Yup, basically exactly that.

I'll see if I can put a PR together today.
