### ISSUE TITLE
Deserializing missing attributes fails

### ISSUE THREAD

**Issue by andrewbanchich** [zenlist/serde_dynamo#52]
I have a struct like:

```rust
#[derive(Debug, Serialize, Deserialize)]
struct Foo {
#[serde(
        deserialize_with = "custom_deser",
        serialize_with = "custom_ser"
    )]
    some_field: bool
}
```

I'm storing this attribute as either a `1` or `null` in DDB (as in `REMOVE some_field` type of null). `custom_deser` and `custom_ser` basically just map the DDB representation to a boolean by deserializing to an `Option<u8>` and checking if it's `Some(1)`, and returning `true` or else returning `false`.

However, this causes deserialization to not work when I delete an item using `REMOVE some_field`. `serde_dynamo` produces:

```bash
Error(
        Message(
            "missing field `some_field`",
        ),
    )
```

I looked into this some more and see that `serde_dynamo` serializes `Option`s to `AttributeValue::Null` types.

Is there a way to get `serde_dynamo` to treat a missing attribute the same as an attribute which exists but is set to `null` so that deserialization works?

**Comment by bryanburgers** [comment]
Yep, this issue is not specific to `serde_dynamo` and is a consequence of how `serde` treats custom serialization/deserialization of options.

The best fix is to add `default` to your field, which will use `bool::default()` if the attribute is not present.

```rust
#[derive(Debug, Serialize, Deserialize)]
struct Foo {
    #[serde(
        default, // <---- HERE!
        deserialize_with = "custom_deser",
        serialize_with = "custom_ser"
    )]
    some_field: bool
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=232d2d026feb287f140a162b6b34f94b

**Comment by andrewbanchich** [comment]
Interesting! Thank you for clarifying.
