### ISSUE TITLE
`serde_dynamo::from_items` not working?

### ISSUE THREAD

**Issue by guidomb** [zenlist/serde_dynamo#54]
Hi! I've just tried deserializing an item using `serde_dynamo::from_items` and `serde_dynamo::from_item` and it seems that the API is not designed to receive a reference to `HashMap<String, aws_sdk_dynamodb::model::AttributeValue` but the example in this crate's documentation seem to indicate otherwise.

 The issue is that AWS DynamoDB SDK [`QueryOutput`](https://docs.rs/aws-sdk-dynamodb/0.21.0/aws_sdk_dynamodb/output/struct.QueryOutput.html) object returns a reference to the hash map when calling the [`items`](https://docs.rs/aws-sdk-dynamodb/0.21.0/aws_sdk_dynamodb/output/struct.QueryOutput.html#method.items).

Am I doing something wrong? Is this the intended behavior? Are the docs out-of-sync?

Thanks!

**Comment by bryanburgers** [comment]
The documentation uses the `.items` *field* which returns owned values, not the `.items()` *method*, which returns a reference. At some point they made the field `#[doc(hidden)]`; I’m not sure why. https://docs.rs/aws-sdk-dynamodb/0.21.0/src/aws_sdk_dynamodb/output.rs.html#1286

**Comment by bryanburgers** [comment]
Thinking about this right now, to make this less confusing. https://github.com/zenlist/serde_dynamo/issues/55#issuecomment-1356404713
