### ISSUE TITLE
Support converting a serde item to a DDB update expression

### ISSUE THREAD

**Issue by DanielBauman88** [zenlist/serde_dynamo#62]
This isn't urgent because I believe the lack of this functionality can be avoided by using the deprecated attribute_updates for update actions and using serde_dynamo to generate the attribute_updates.

However, it would be nice to support an update expression so that consumers of this library don't need to use the deprecated methods.

(If this is already supported somewhere please let me know!)

**Comment by bryanburgers** [comment]
I usually use something that looks like the following. Is this what you're looking for, or are you asking a different question?

```rust
use serde_dynamo::to_attribute_value;

let id = String::from("some-id");
let some_value = /* Anything that can be serialized */;

dynamodb_client
    .update_item()
    .table_name("some-table")
    .key("id", to_attribute_value(id)?)
    .update_expression("SET some_field = :some_value")
    .expression_attribute_values(":some_value", to_attribute_value(some_value)?)
    .send()
    .await?;
```

**Comment by bryanburgers** [comment]
The examples in https://docs.rs/serde_dynamo/latest/serde_dynamo/fn.to_attribute_value.html could probably be updated, if you're willing to submit a PR.
