### ISSUE TITLE
Item's Serialize not equivalent to serde_json's output

### ISSUE THREAD

**Issue by tomtau** [zenlist/serde_dynamo#81]
Not sure if a duplicate of https://github.com/zenlist/serde_dynamo/issues/80 or if it's expected as per: https://docs.rs/serde_dynamo/latest/serde_dynamo/#converting-to-and-from-dynamodb-json

This code fails:
```rust
let s = MyStruct {
    value: "hello".to_string(),
};

let value = serde_json::to_value(s.clone()).unwrap();
let item: serde_dynamo::Item = serde_dynamo::to_item(s).unwrap();
let value2 = serde_json::to_value(item.clone()).unwrap();
assert_eq!(value, value2);
```

If it's expected, it'd be worth adding more clarification in docs (e.g. `Item` / `AttributeValue` can be used as types on their own, but should not appear in another parent struct that also implements Serialize etc.).

**Comment by bryanburgers** [comment]
Yep, this code is _not_ expected to succeed. The serialization and deserialization for `serde_dynamo::Item` specifically uses the DynamoDB JSON format that describes itself.

For example,

```rust
let item = serde_dynamo::AttributeValue::M(HashMap::from([
  (String::from("name"), serde_dynamo::AttributeValue::S(String::from("Arthur Dent"))),
  (String::from("age"), serde_dynamo::AttributeValue::N(String::from("42"))),
]));

let dynamodb_json = serde_json::to_string_pretty(&item).unwrap();
```

is expected to output

```json
{
  "M": {
    "age": {
      "N": "42"
    },
    "name": {
      "S": "Arthur Dent"
    }
  }
}
```

and not something like

```json
{
  "age": 42,
  "name": "Arthur Dent"
}
```
